exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.lock.json
  - package.json
  - webpack.config.js
  - src
plugins:
  - jekyll-haml
sass:
    sass_dir: assets/stylesheets
    style: compressed
url: https://allenjgreer.github.io
