exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.lock.json
  - package.json
  - webpack.config.js
  - src
url: https://allenjgreer.github.io
sass:
    sass_dir: assets/stylesheets
    style: compressed
