exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.lock.json
  - package.json
  - webpack.config.js
  - src
  - .editorconfig
  - .eslintignore
  - .eslintrc.js
